const SUPABASE_URL = 'https://evsojjnzajvhvxmlmshc.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2c29qam56YWp2aHZ4bWxtc2hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY1NjQzODcsImV4cCI6MjA5MjE0MDM4N30.Wj-cuMCkdJGGUP7OInXfzJFQmnLh8M0sdUqsULMg4no';
supabase = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

